config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  post 'dashboard', to: 'dashboard#write', as: 'write_file'
  get 'read_file', to: 'dashboard#read', as: 'read_file'
  get 'read_csv', toL 'dashboard#read_csv', as: 'read_csv'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	require 'csv'

  def index
  end

  def read_csv
  	csv_file = "#{File.expand_path(".")}/tmp/user.csv"
  	users = []
  	CSV.foreach(csv_file, { headers: true, header_converters: :symbol }) do |row|
  		users << row.to_hash
  	end
  end

  def write_csv
  	CSV.open("tmp/my_file.csv", "wb") do |csv|
  		csv << ['this', 'is', 'a', 'row']
  		csv << ['this', 'is', 'another', 'row']
  	end
  end

  def write
  	path = "#{File.expand_path(".")}/tmp/"
  	File.open("#{path}#{params[:file][:filename]}", "wb") do |file|
  		begin
  			file.write(params[:file][:content])
  		rescue => e
  			logger.error e.messages
  		end
  	end
	  redirect_to :root
  end

  def read
  	base_file = "#{File.expand_path(".")}/tmp/my_file.txt"
  	File.open(file, 'r') do |file|
  		@content = file.read
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%h2 File Practice
%hr
= form_for :file, url: write_file_path do |f|
	= f.label :filename
	= f.text_field :filename
	= f.label :content
	= f.text_area :content
	= f.submit :create_file

= link_to 'Read File', read_file_path

app/views/dashboard/read.html.haml
%p
	= simple_format(@content)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FilePractice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>